# Generated by Django 4.2.3 on 2023-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
